### ISSUE TITLE
[Crash] Creature::executeConditions 

### ISSUE THREAD

**Issue by HyugaMx** [nekiro/forgottenserver-1.3-8.6#1]
Steps to reproduce (include any configuration/script required to reproduce)
Use an onPrepareDeath script which removes one condition or more with the help of Creature.removeCondition. However you can bypass the crash if you replace L9 with condition:setTicks(0), but it doesn't remove the condition immediately.
Kill your target with a dot (damage-over-time) spell or rune.
Expected behaviour
Removes the condition safely.

Actual behaviour
Server crashes. It might not always crash for you, but it did for me at least.

**Comment by Znote** [comment]
This is a downport of otland/forgottenserver master. 
The issue your talking about is this: https://github.com/otland/forgottenserver/issues/2024

A fix has been implemented and is undergoing some final code reviews:
https://github.com/otland/forgottenserver/pull/2541

Once it gets merged to master, it will be appropriate to sync over here. Until then you can manually [apply the fix](https://github.com/otland/forgottenserver/pull/2541/files).

**Comment by nekiro** [comment]
Hi @HyugaMx, as @Znote said. This is master branch forgottenserver issue, I will update this repository, when the forgottenserver will fix it, because I saw it's almost fixed already.

**Comment by nekiro** [comment]
Should be fixed with b69005c90e2c2618cbe566f8b2c2cdd97c318e7f
