### ISSUE TITLE
Question Pack Monsters

### ISSUE THREAD

**Issue by gregorecruzeiro** [nekiro/forgottenserver-1.3-8.6#2]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1.
2.
3.

### Environment

in the forgottenserver repository, the attacks are as in the example below.

<attack name = "melee" interval = "2000" **min = "0" max = "- 45**" />

Already in your repository is

<attack name = "melee" interval = "2000" **skill = "20" attack = "30"** />

The first one uses **min and max** and its uses **skill and attack**, does not this problem, since it uses TFS 1.3?
It's not critical, just a question, because I do not understand very well.

**Comment by nekiro** [comment]
No, tfs can use both versions for melee attacks. You can use min max or skill and attack.
