### ISSUE TITLE
random Crash

### ISSUE THREAD

**Issue by mattyx14** [nekiro/forgottenserver-1.3-8.6#3]
Client / random crash, for example, I call ferumbras and I start to fight and after a few seconds the client fails with the moveCreature function

**Comment by nekiro** [comment]
Does it happen on all monsters or only on this one? If on this one then its specific to the monster, something is wrong with him. I dont know what is moveCreature function in client, so if you can show me the debug log from the client.

**Comment by mattyx14** [comment]
I revert new change on condition and error no appear

**Comment by nekiro** [comment]
How is it even possible that these changes would affect client to the point it debugs?

**Comment by gregorecruzeiro** [comment]
> Client / random crash, for example, I call ferumbras and I start to fight and after a few seconds the client fails with the moveCreature function

In my client I also suffer from these debugs, as corrected?

**Comment by nekiro** [comment]
Should be fixed with https://github.com/nekiro/forgottenserver-1.3-8.6/commit/91450cd1bbd1c0661a497717db05324ecc0bcf5c
