### ISSUE TITLE
Schema.sql

### ISSUE THREAD

**Issue by Eternym** [nekiro/forgottenserver-1.3-8.6#5]
Schema.sql file is incomplete.
Some tables are missing like 'houses'
The missing tables make every character relog reset your character position to spawn

![](https://i.gyazo.com/94966ca0058401737a0e803c06a6ccda.png)

And this is going on in console during relog

![](https://i.gyazo.com/e25c3c0322f01d96ddb7e96cd2c39b17.png)

![](https://i.gyazo.com/d9f8dbc8e1478c64e4d507d2d87a3377.png)

**Comment by nekiro** [comment]
Open and look the code, none of these tables you listed are missing.

**Comment by Eternym** [comment]
Why does this happen then? A friend on otland had same problem

**Comment by nekiro** [comment]
Reimport your schema sql, last commit was fixing one error regarding schema.
