### ISSUE TITLE
Depot Items are not saving after relog

### ISSUE THREAD

**Issue by xBudex** [nekiro/forgottenserver-1.3-8.6#6]
So as the title says, Once you put item into LOCKER not DEPOT and relog, your items are gone.
but if you put your items into DEPOT and not LOCKER your items will stay so.
![unknown](https://user-images.githubusercontent.com/48287477/55283424-250d3100-5363-11e9-84a7-acfc075fc4d8.png)
And after relog, items are gone..

**Comment by Znote** [comment]
This should probably be added to data/events/scripts/player.lua as well: (why is it removed? Code is from main repo). 

`function Player:onMoveItem(item, count, fromPosition, toPosition)`
```lua
if toPosition.x ~= CONTAINER_POSITION then
	return true
end

if item:getTopParent() == self and bit.band(toPosition.y, 0x40) == 0 then
	local itemType, moveItem = ItemType(item:getId())
	if bit.band(itemType:getSlotPosition(), SLOTP_TWO_HAND) ~= 0 and toPosition.y == CONST_SLOT_LEFT then
		moveItem = self:getSlotItem(CONST_SLOT_RIGHT)
	elseif itemType:getWeaponType() == WEAPON_SHIELD and toPosition.y == CONST_SLOT_RIGHT then
		moveItem = self:getSlotItem(CONST_SLOT_LEFT)
		if moveItem and bit.band(ItemType(moveItem:getId()):getSlotPosition(), SLOTP_TWO_HAND) == 0 then
			return true
		end
	end

	if moveItem then
		local parent = item:getParent()
		if parent:getSize() == parent:getCapacity() then
			self:sendTextMessage(MESSAGE_STATUS_SMALL, Game.getReturnMessage(RETURNVALUE_CONTAINERNOTENOUGHROOM))
			return false
		else
			return moveItem:moveTo(parent)
		end
	end
end
return true
```

`data/events/events.xml`
```xml
<event class="Player" method="onMoveItem" enabled="1" />
```

**Comment by nekiro** [comment]
@Znote why, should this code be added?
About the issue, your locker should be capacity 1, which contains only depot. So this issue is invalid.

**Comment by Znote** [comment]
@nekiro Because its there in the main repo.

https://github.com/nekiro/forgottenserver-1.3-8.6/blob/master/data/items/items.xml#L4322
```xml
	<item fromid="2589" toid="2592" article="a" name="locker">
		<attribute key="type" value="depot" />
		<attribute key="containerSize" value="3" />
	</item>
```

**Comment by nekiro** [comment]
If its in main repo it doesnt mean it has to be here. This code is for wepon swap from two handed to one handed with shield, it will deequip the shield and equip one handed weapon. This didnt exist in tibia 8.6 afaik, so this code was removed.

**Comment by Znote** [comment]
> About the issue, your locker should be capacity 1, which contains only depot. So this issue is invalid.

Where do you change this? Done it in items.xml, it says the locker is vol 1. But you can still place lots of items in it.

**Comment by xBudex** [comment]
> > About the issue, your locker should be capacity 1, which contains only depot. So this issue is invalid.
> 
> Where do you change this? Done it in items.xml, it says the locker is vol 1. But you can still place lots of items in it.

Yep I agree.
In items.xml if you put 1 or 2, it still loads locker with 32 spots.

**Comment by Znote** [comment]
> I would need more info about this issue, how depot worked in 8.6 client. Was locker global and depot per town?

Both locker and depot was per town. The only difference is that the locker would be the container to get parcels and letters when this was being sent to you. In 8.6 there was no auction or mailbox, so it just got thrown directly into the locker.
