### ISSUE TITLE
Parcel/Letter

### ISSUE THREAD

**Issue by MustafaLegend1337** [nekiro/forgottenserver-1.3-8.6#7]
Server crashes immediately when I send a parcel or letter, I tried different cities Thais/Carlin and different mailboxes and it is all same still getting crashed.
![howt](https://user-images.githubusercontent.com/26151402/55446476-1b343980-55c0-11e9-9011-a6eabe9b5142.JPG)

**Comment by nekiro** [comment]
Please include crash log
